# name: Expo Publish
# on:
#   push:
#     tags:
#       - "v*"
# jobs:
#   publish:
#     runs-on: ubuntu-latest
#     steps:
#       - name: ğŸ— Setup repo
#         uses: actions/checkout@v2

#       - name: ğŸ— Setup Node
#         uses: actions/setup-node@v2
#         with:
#           node-version: 16.x
#           cache: yarn

#       - name: ğŸ— Setup Expo
#         uses: expo/expo-github-action@v7
#         with:
#           expo-version: latest
#           token: ${{ secrets.EXPO_TOKEN }}

#       - name: ğŸ“¦ Install dependencies
#         run: yarn install

#       - name: ğŸš€ Publish app
#         run: expo publish --non-interactive
